Repository jei-community/frontend, pull requests merged in 2024-12, with the labels that each got.

#2 🐛 fix: vitest config 타입 에러 해결
  vite.config.ts
Labels: bug

#6 Docs/pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#4 docs: issue template 초안 작성
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
Labels: documentation

#8 레이아웃 컴포넌트 구현
  src/App.tsx
  src/components/Layout/Header/index.tsx
  src/components/Layout/SideAside/index.tsx
  src/components/Layout/index.tsx
  src/styles/GlobalStyle/index.tsx
Labels: feature

#16 👷 build: github action 자동 배포 yml 작성
  .github/workflows/deploy.yml
Labels: build

#14 Feature/globalstyle
  src/App.tsx
  src/pages/Main/index.tsx
  src/styles/GlobalStyle/index.tsx
  src/styles/theme/colors.ts
  src/styles/theme/emotion.d.ts
  src/styles/theme/index.ts
  src/styles/theme/typography.ts
Labels: feature

#18 Feature/scroll
  src/components/DraggableScroll/hooks/useDraggable.ts
  src/components/DraggableScroll/index.tsx
  src/components/DraggableScroll/style.ts
  src/pages/Main/index.tsx
  src/pages/Main/style.ts
  src/styles/GlobalStyle/index.tsx
  src/utils/common.ts
  src/utils/index.ts
Labels: feature

#20 Feat/sign in
  src/Router.tsx
  src/pages/SignIn/assets/background.png
  src/pages/SignIn/assets/google-logo.svg
  src/pages/SignIn/index.tsx
  src/pages/SignIn/style.ts
  src/styles/assets/images/logo_white.svg
  src/styles/theme/typography.ts
Labels: feature

#24 레이아웃 전체적인 구조 수정
  src/components/Aside/index.tsx
  src/components/Aside/style/aside.ts
  src/components/Aside/style/index.ts
  src/components/Content/index.tsx
  src/components/Content/style/content.ts
  src/components/Content/style/index.ts
  src/components/Layout/Header/index.tsx
  src/components/Layout/Header/style/header.ts
  src/components/Layout/Header/style/index.ts
  src/components/Layout/SideAside/index.tsx
  src/components/Layout/index.tsx
  src/components/Layout/style/index.ts
  src/components/Layout/style/layout.ts
  src/constants/index.ts
  src/constants/style.ts
Labels: refactor

#23 Feat/sign in
  src/pages/SignIn/index.tsx
  src/pages/SignIn/style/index.ts
Labels: refactor

#28 Feature/scroll
  src/components/DraggableScroll/style/index.ts
  src/components/Layout/style/layout.ts
  src/pages/Main/index.tsx
  src/pages/Main/style/index.ts
  src/utils/common.ts
Labels: bug, refactor

#36 👷 build: svgr, lucide-react 패키지 설치
  package-lock.json
  package.json
  src/vite-env.d.ts
  svg.d.ts
  tsconfig.json
  vite.config.ts
Labels: build

#37 Projects 페이지 퍼블리싱
  src/Router.tsx
  src/components/Aside/style/aside.ts
  src/components/Content/hooks/index.ts
  src/components/Content/hooks/useAsideCount.ts
  src/components/Content/index.tsx
  src/components/Content/style/content.ts
  src/components/Divider/index.tsx
  src/components/Divider/style/divider.ts
  src/components/Divider/style/index.ts
  src/components/Layout/index.tsx
  src/components/Layout/style/layout.ts
  src/constants/style.ts
  src/pages/Projects/assets/icons/glass.svg
  src/pages/Projects/assets/icons/index.ts
  src/pages/Projects/assets/icons/left-chevron-first.svg
  src/pages/Projects/assets/icons/left-chevron.svg
  src/pages/Projects/assets/icons/right-chevron-last.svg
  src/pages/Projects/assets/icons/right-chevron.svg
  src/pages/Projects/assets/index.ts
  src/pages/Projects/components/Project.tsx
  src/pages/Projects/components/style/index.ts
  src/pages/Projects/components/style/project.ts
  src/pages/Projects/index.tsx
  src/pages/Projects/style/index.ts
  src/pages/Projects/style/projects.ts
  src/styles/GlobalStyle/index.tsx
Labels: feature

#43 ✨ feat : 아티클 페이지 및 컴포넌트 생성
  src/Router.tsx
  src/pages/Articles/components/Post.tsx
  src/pages/Articles/components/style/index.ts
  src/pages/Articles/components/style/post.ts
  src/pages/Articles/index.tsx
  src/pages/Articles/style/index.ts
Labels: feature

#38 공통 버튼 컴포넌트 구현
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/preview.tsx
  src/components/Button/index.tsx
  src/components/Button/stories/Button.stories.ts
  src/components/Button/style/index.ts
  src/components/Button/types/index.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: feature

#46 Project 상세 페이지 구현
  src/Router.tsx
  src/components/Aside/index.tsx
  src/components/Aside/style/aside.ts
  src/components/Content/hooks/index.ts
  src/components/Content/hooks/useAsideCount.ts
  src/components/Content/hooks/useAsideInfo.ts
  src/components/Content/index.tsx
  src/components/Content/style/content.ts
  src/components/Content/types/aside.ts
  src/components/Content/types/index.ts
  src/components/Layout/constants/style.ts
  src/constants/style.ts
  src/pages/Project/components/DescriptionContainer/index.tsx
  src/pages/Project/components/DescriptionContainer/style/index.ts
  src/pages/Project/components/HyperlinkList/index.tsx
  src/pages/Project/components/HyperlinkList/style/index.ts
  src/pages/Project/components/TableOfContent/index.tsx
  src/pages/Project/components/TableOfContent/style/index.ts
  src/pages/Project/components/TechStackAndEnvContainer/index.tsx
  src/pages/Project/components/TechStackAndEnvContainer/style/index.ts
  src/pages/Project/components/TitleContainer/index.tsx
  src/pages/Project/components/TitleContainer/style/index.ts
  src/pages/Project/index.tsx
  src/pages/Project/style/index.ts
  src/pages/Projects/components/ProjectCard.tsx
  src/pages/Projects/components/style/index.ts
  src/pages/Projects/components/style/projectCard.ts
  src/pages/Projects/index.tsx
  src/styles/GlobalStyle/index.tsx
Labels: feature

#51 공통 텍스트 필드 & 텍스트 에리어 컴포넌트 구현
  src/components/Button/style/index.ts
  src/components/TextArea/index.tsx
  src/components/TextArea/stories/TextArea.stories.ts
  src/components/TextArea/style/index.ts
  src/components/TextField/index.tsx
  src/components/TextField/stories/TextField.stories.ts
  src/components/TextField/style/index.ts
  src/components/TextField/types/index.ts
Labels: feature

#50 메인 페이지 퍼블리싱
  src/components/Content/style/content.ts
  src/components/DraggableScroll/hooks/useDraggable.ts
  src/components/DraggableScroll/index.tsx
  src/pages/Main/assets/index.tsx
  src/pages/Main/assets/thumbnail-example.png
  src/pages/Main/components/Article/ArticleItem.tsx
  src/pages/Main/components/Article/style/index.ts
  src/pages/Main/components/MyProject/MyProjectItem.tsx
  src/pages/Main/components/MyProject/style/index.ts
  src/pages/Main/components/Post/PostItem.tsx
  src/pages/Main/components/Post/style/index.ts
  src/pages/Main/components/ReadMoreButton/index.tsx
  src/pages/Main/components/ReadMoreButton/style/index.ts
  src/pages/Main/components/index.ts
  src/pages/Main/hooks/useClampCheck.ts
  src/pages/Main/index.tsx
  src/pages/Main/style/index.ts
Labels: feature

#54 리뷰 알림 추가
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  .github/workflows/pr-google-chat-alert.yml
Labels: chore

#60 프로젝트 에디터 페이지 1차 구현
  src/Router.tsx
  src/components/TechStackList/index.tsx
  src/mocks/data/project.ts
  src/pages/Project/components/Title/index.tsx
  src/pages/ProjectEditor/components/ButtonWithIcon/index.tsx
  src/pages/ProjectEditor/components/ButtonWithIcon/style/index.ts
  src/pages/ProjectEditor/components/CancelButton/index.tsx
  src/pages/ProjectEditor/components/DeleteButton/index.tsx
  src/pages/ProjectEditor/components/DescriptionEditor/index.tsx
  src/pages/ProjectEditor/components/DocumentTooltipList/index.tsx
  src/pages/ProjectEditor/components/DocumentTooltipList/style/index.ts
  src/pages/ProjectEditor/components/EnvEditor/index.tsx
  src/pages/ProjectEditor/components/Modal/index.tsx
  src/pages/ProjectEditor/components/SaveButton/index.tsx
  src/pages/ProjectEditor/components/TechStackEditor/index.tsx
  src/pages/ProjectEditor/components/TechStackEditor/style/index.ts
  src/pages/ProjectEditor/components/TitleEditor/components/MemberEditor/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/components/ProjectTitleEditor/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/components/ThumbnailEditor/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/style/index.ts
  src/pages/ProjectEditor/index.tsx
  src/pages/Projects/assets/icons/glass.svg
  src/pages/Projects/assets/icons/index.ts
  src/pages/Projects/assets/icons/left-chevron-first.svg
  src/pages/Projects/assets/icons/left-chevron.svg
  src/pages/Projects/assets/icons/right-chevron-last.svg
  src/pages/Projects/assets/icons/right-chevron.svg
  src/pages/Projects/assets/index.ts
  src/pages/Projects/components/ProjectCard.tsx
  src/pages/Projects/index.tsx
  src/styles/GlobalStyle/index.tsx
Labels: feature

#58 ✨ feat : 일일점검 페이지 1차 작업
  src/Router.tsx
  src/apis/dailyCheck/index.ts
  src/constants/path.ts
  src/pages/DailyCheck/components/CheckBox.tsx
  src/pages/DailyCheck/components/EmptyContent.tsx
  src/pages/DailyCheck/components/MainContent.tsx
  src/pages/DailyCheck/components/TBodyContent.tsx
  src/pages/DailyCheck/components/Table.tsx
  src/pages/DailyCheck/components/style/index.ts
  src/pages/DailyCheck/components/style/table.ts
  src/pages/DailyCheck/constant/index.ts
  src/pages/DailyCheck/index.tsx
  src/pages/DailyCheck/style/index.ts
  src/pages/Swagger/index.tsx
Labels: feature

#62 포스트페이지 라우터 추가 & 마크다운 에디터 구현
  package-lock.json
  package.json
  src/Router.tsx
  src/constants/path.ts
  src/pages/Post/components/Editor/index.tsx
  src/pages/Post/components/Editor/style/index.ts
  src/pages/Post/components/List/index.tsx
  src/pages/Post/components/MarkdownEditor/index.tsx
  src/pages/Post/components/MarkdownEditor/style/index.ts
  src/pages/Post/components/PostingLink/index.tsx
  src/pages/Post/components/PostingLink/style/index.ts
  src/pages/Post/index.tsx
Labels: feature

#65 프로젝트 페이지 라우트 구조 수정
  src/Router.tsx
  src/constants/path.ts
  src/pages/ProjectEditor/components/DocumentTooltipList/index.tsx
  src/pages/ProjectEditor/components/SaveButton/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/style/index.ts
  src/pages/ProjectItem/components/Description/index.tsx
  src/pages/ProjectItem/components/Description/style/index.ts
  src/pages/ProjectItem/components/EditorLink/index.tsx
  src/pages/ProjectItem/components/EditorLink/style/index.ts
  src/pages/ProjectItem/components/Env/index.tsx
  src/pages/ProjectItem/components/Env/style/index.ts
  src/pages/ProjectItem/components/TableOfContent/index.tsx
  src/pages/ProjectItem/components/TableOfContent/style/index.ts
  src/pages/ProjectItem/components/TechStack/index.tsx
  src/pages/ProjectItem/components/Title/index.tsx
  src/pages/ProjectItem/components/Title/style/index.ts
  src/pages/ProjectItem/components/TooltipList/index.tsx
  src/pages/ProjectItem/components/TooltipList/style/index.ts
  src/pages/ProjectItem/index.tsx
  src/pages/ProjectList/components/ProjectCard.tsx
  src/pages/ProjectList/components/style/index.ts
  src/pages/ProjectList/components/style/projectCard.ts
  src/pages/ProjectList/index.tsx
  src/pages/ProjectList/router/index.tsx
  src/pages/ProjectList/style/index.ts
  src/pages/ProjectList/style/projects.ts
  src/pages/ProjectRouter/index.tsx
Labels: refactor

#67 feat: 외부 문서 링크 모달 UI 구현
  src/pages/ProjectEditor/components/DocumentTooltipList/index.tsx
  src/pages/ProjectEditor/components/DocumentTooltipList/style/index.ts
Labels: feature

#69 프로젝트 리스트 페이지 내 프로젝트 토글 UI 구현
  src/components/Content/style/content.ts
  src/pages/ProjectList/index.tsx
  src/pages/ProjectList/style/index.ts
  src/pages/ProjectList/style/projectList.ts
Labels: feature

#71 프로젝트 페이지 라우트 오류 수정
  src/pages/ProjectEditor/components/CancelButton/index.tsx
  src/pages/ProjectEditor/components/DeleteButton/index.tsx
  src/pages/ProjectEditor/components/SaveButton/index.tsx
  src/pages/ProjectItem/components/EditorLink/index.tsx
Labels: bug

#75 텍스트 버튼, 아바타, 체크박스 컴포넌트 구현 및 스토리 추가
  src/components/Avatar/index.tsx
  src/components/Avatar/stories/Avatar.stories.ts
  src/components/Avatar/style/index.ts
  src/components/Avatar/types/index.ts
  src/components/Button/index.tsx
  src/components/Button/style/index.ts
  src/components/Checkbox/index.tsx
  src/components/Checkbox/stories/Checkbox.stories.tsx
  src/components/Checkbox/style/index.ts
  src/components/TextButton/index.tsx
  src/components/TextButton/stories/TextButton.stories.ts
  src/components/TextButton/style/index.ts
  src/components/TextButton/types/index.ts
  src/components/TextField/index.tsx
  src/components/TextField/style/index.ts
Labels: feature

#74 프로젝트 페이지 스웨거 명세의 데이터로 교체
  src/components/TechStackList/index.tsx
  src/constants/common.ts
  src/mocks/data/project.ts
  src/pages/ProjectItem/components/Description/index.tsx
  src/pages/ProjectItem/components/Env/index.tsx
  src/pages/ProjectItem/components/Env/style/index.ts
  src/pages/ProjectItem/components/TechStack/index.tsx
  src/pages/ProjectItem/components/Title/index.tsx
  src/pages/ProjectItem/components/Title/style/index.ts
  src/pages/ProjectItem/components/TooltipList/index.tsx
  src/pages/ProjectItem/index.tsx
  src/pages/ProjectList/index.tsx
  src/pages/ProjectList/style/projectList.ts
  src/types/project.ts
Labels: refactor

#78 일일점검 페이지 작업 1차 완료
  src/apis/dailyCheck/constant/index.ts
  src/apis/dailyCheck/index.ts
  src/apis/dailyCheck/test.ts
  src/apis/dailyCheck/type/index.ts
  src/components/HtmlParser/index.tsx
  src/pages/DailyCheck/components/CheckBox.tsx
  src/pages/DailyCheck/components/MainContent.tsx
  src/pages/DailyCheck/components/MainContent/EmptyContent.tsx
  src/pages/DailyCheck/components/MainContent/index.tsx
  src/pages/DailyCheck/components/SIdeContent/index.tsx
  src/pages/DailyCheck/components/SIdeContent/style/index.ts
  src/pages/DailyCheck/components/TBodyContent.tsx
  src/pages/DailyCheck/components/Table.tsx
  src/pages/DailyCheck/components/Table/CheckBox.tsx
  src/pages/DailyCheck/components/Table/TBodyDefault.tsx
  src/pages/DailyCheck/components/Table/TBodyManager.tsx
  src/pages/DailyCheck/components/Table/TBodyMemo.tsx
  src/pages/DailyCheck/components/Table/TBodyTodo.tsx
  src/pages/DailyCheck/components/Table/TBodyWrapper.tsx
  src/pages/DailyCheck/components/Table/index.tsx
  src/pages/DailyCheck/components/Table/style/index.ts
  src/pages/DailyCheck/components/Tooltip/CheckTooltip.tsx
  src/pages/DailyCheck/components/Tooltip/MemoTooltip.tsx
  src/pages/DailyCheck/components/Tooltip/index.tsx
  src/pages/DailyCheck/components/Tooltip/style/index.ts
  src/pages/DailyCheck/components/style/index.ts
  src/pages/DailyCheck/constant/index.ts
  src/pages/DailyCheck/index.tsx
  src/pages/DailyCheck/store/index.ts
  src/pages/DailyCheck/style/index.ts
  src/pages/DailyCheck/type/index.ts
Labels: feature

#81 프로젝트 리스트 페이지 데이터 연결
  src/mocks/data/project.ts
  src/pages/ProjectItem/components/Title/index.tsx
  src/pages/ProjectItem/components/Title/style/index.ts
  src/pages/ProjectList/components/ProjectCard.tsx
  src/pages/ProjectList/components/ProjectCard/index.tsx
  src/pages/ProjectList/components/ProjectCard/style/index.ts
  src/pages/ProjectList/components/ProjectListToggle/index.tsx
  src/pages/ProjectList/components/ProjectListToggle/style/index.ts
  src/pages/ProjectList/components/Searchbar/index.tsx
  src/pages/ProjectList/components/Searchbar/style/index.ts
  src/pages/ProjectList/components/style/index.ts
  src/pages/ProjectList/components/style/projectCard.ts
  src/pages/ProjectList/index.tsx
  src/pages/ProjectList/style/index.ts
  src/pages/ProjectList/style/projectList.ts
  src/types/project.ts
Labels: feature, refactor

#82 로딩 스피너, 빈 내용 영역, 토글 스위치 컴포넌트 구현 및 스토리 추가
  src/components/Avatar/style/index.ts
  src/components/Button/style/index.ts
  src/components/EmptyContent/index.tsx
  src/components/EmptyContent/stories/EmptyContent.stories.ts
  src/components/EmptyContent/style/index.ts
  src/components/EmptyContent/types/index.ts
  src/components/LoadingSpinner/index.tsx
  src/components/LoadingSpinner/stories/LoadingSpinner.stories.ts
  src/components/LoadingSpinner/style/index.ts
  src/components/LoadingSpinner/types/index.ts
  src/components/TextField/style/index.ts
  src/components/ToggleSwitch/index.tsx
  src/components/ToggleSwitch/stories/ToggleSwitch.stories.tsx
  src/components/ToggleSwitch/style/index.ts
Labels: feature

#84 API 파일 리팩토링
  src/apis/dailyCheck/index.ts
  src/apis/dailyCheck/test.ts
  src/apis/dailyCheck/util/index.ts
  src/pages/DailyCheck/components/Tooltip/CheckTooltip.tsx
Labels: refactor

#88 앨범 에디터에 이미지 드래그 앤 드롭 적용
  src/pages/AlbumEditor/components/ImageUploadBox/index.tsx
  src/pages/AlbumEditor/components/ImageUploadBox/style/index.ts
  src/pages/AlbumEditor/constant/index.ts
  src/pages/AlbumEditor/index.tsx
  src/pages/Main/index.tsx
  src/pages/Main/style/index.ts
  src/pages/PostEditor/index.tsx
  src/pages/PostEditor/style/index.ts
  src/pages/PostList/index.tsx
  src/pages/PostList/style/index.ts
  src/types/album.ts
Labels: feature

#89 메인 내 일일점검
  src/apis/dailyCheck/constant/index.ts
  src/apis/dailyCheck/index.ts
  src/apis/dailyCheck/type/index.ts
  src/pages/Main/components/DailyCheck/Item.tsx
  src/pages/Main/components/DailyCheck/ItemsWrapper.tsx
  src/pages/Main/components/DailyCheck/index.tsx
  src/pages/Main/components/DailyCheck/style/index.ts
  src/pages/Main/index.tsx
Labels: feature

#91 프로젝트 에디터 페이지 목업데이터, form 데이터 연결
  src/Router.tsx
  src/components/TechStack/index.tsx
  src/components/TechStack/style/index.ts
  src/constants/path.ts
  src/mocks/data/project.ts
  src/pages/ProjectEditor/components/ButtonWithIcon/index.tsx
  src/pages/ProjectEditor/components/ButtonWithIcon/style/index.ts
  src/pages/ProjectEditor/components/CancelButton/index.tsx
  src/pages/ProjectEditor/components/DescriptionEditor/index.tsx
  src/pages/ProjectEditor/components/EnvEditor/index.tsx
  src/pages/ProjectEditor/components/SaveButton/index.tsx
  src/pages/ProjectEditor/components/TechStackEditor/components/DefaultTechStacks/index.tsx
  src/pages/ProjectEditor/components/TechStackEditor/components/EditableTechStacks/index.tsx
  src/pages/ProjectEditor/components/TechStackEditor/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/components/MemberEditor/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/components/ProjectTitleEditor/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/components/ThumbnailEditor/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/index.tsx
  src/pages/ProjectEditor/index.tsx
  src/pages/ProjectItem/ProjectItemRouter/index.tsx
  src/pages/ProjectItem/components/EditorLink/index.tsx
  src/pages/ProjectItem/components/TechStack/index.tsx
  src/pages/ProjectList/components/Searchbar/index.tsx
  src/pages/ProjectList/hooks/index.ts
  src/pages/ProjectList/hooks/useIsMyProjectSelected.ts
  src/pages/ProjectList/hooks/useProjectList.ts
  src/pages/ProjectList/index.tsx
Labels: feature, refactor

#95 ✨ feat : 메인 일일점검 데이터 없을 때 처리
  src/apis/dailyCheck/constant/index.ts
  src/pages/DailyCheck/index.tsx
  src/pages/Main/components/DailyCheck/Item.tsx
  src/pages/Main/components/DailyCheck/ItemsWrapper.tsx
  src/pages/Main/components/DailyCheck/index.tsx
  src/pages/Main/components/DailyCheck/style/index.ts
Labels: feature

#99 build: npm 설치 명령어 수정
  .github/workflows/deploy.yml
  package.json
  src/pages/ProjectEditor/components/TitleEditor/components/ProjectTitleEditor/index.tsx
  tsconfig.tsbuildinfo
Labels: build

#103 일일점검 관련 컴포넌트에 로딩 컴포넌트 추가
  src/pages/DailyCheck/components/Loading/index.tsx
  src/pages/DailyCheck/components/Loading/style/index.ts
  src/pages/DailyCheck/index.tsx
  src/pages/Main/components/DailyCheck/Loading.tsx
  src/pages/Main/components/DailyCheck/index.tsx
  src/pages/Main/components/DailyCheck/style/index.ts
Labels: feature

#108 feat: 임시 헤더 추가
  src/components/Layout/Header/assets/avatar.svg
  src/components/Layout/Header/assets/logo.svg
  src/components/Layout/Header/index.tsx
  src/components/Layout/Header/style/header.ts
  src/components/Layout/Header/style/index.ts
Labels: feature

#104 메인페이지 포스트 MD형식 렌더링 & 포스트 내용 입력 안 했을 때 오류 수정
  src/pages/Main/components/Post/PostItem.tsx
  src/pages/Main/components/Post/style/index.ts
  src/pages/Main/index.tsx
  src/pages/PostEditor/components/MarkdownEditor/index.tsx
  src/utils/common.ts
Labels: feature

#114 앨범 리스트 페이지 UI 구현
  src/components/Profile/index.tsx
  src/components/Profile/style/index.ts
  src/pages/AlbumList/component/AlbumItem/AlbumItem.tsx
  src/pages/AlbumList/component/AlbumItem/style/index.ts
  src/pages/AlbumList/index.tsx
  src/pages/AlbumList/style/index.ts
  src/pages/PostList/components/EditorLink/index.tsx
  src/pages/PostList/components/EditorLink/style/index.ts
  src/pages/PostList/index.tsx
Labels: feature

#119 뱃지, 버튼 그룹, 모달 컴포넌트 구현 및 스토리 추가
  src/components/Avatar/stories/Avatar.stories.ts
  src/components/Badge/index.tsx
  src/components/Badge/stories/Badge.stories.ts
  src/components/Badge/style/index.ts
  src/components/Badge/types/index.ts
  src/components/Button/stories/Button.stories.ts
  src/components/ButtonGroup/index.tsx
  src/components/ButtonGroup/stories/ButtonGroup.stories.tsx
  src/components/ButtonGroup/style/index.ts
  src/components/ButtonGroup/types/index.ts
  src/components/Checkbox/stories/Checkbox.stories.tsx
  src/components/EmptyContent/stories/EmptyContent.stories.ts
  src/components/LoadingSpinner/stories/LoadingSpinner.stories.ts
  src/components/Modal/index.tsx
  src/components/Modal/store/index.ts
  src/components/Modal/stories/Modal.stories.tsx
  src/components/Modal/style/index.ts
  src/components/Modal/types/index.ts
  src/components/TextArea/stories/TextArea.stories.ts
  src/components/TextButton/stories/TextButton.stories.ts
  src/components/TextField/stories/TextField.stories.ts
  src/components/ToggleSwitch/stories/ToggleSwitch.stories.tsx
  src/styles/theme/typography.ts
Labels: feature

#121 ScrollToTop 컴포넌트 구현
  src/App.tsx
  src/components/Layout/Header/style/index.ts
  src/components/Layout/style/layout.ts
  src/components/ScrollToTop/index.tsx
  src/pages/ProjectEditor/components/Modal/index.tsx
  src/pages/ProjectEditor/style/index.ts
  src/pages/ProjectItem/components/TableOfContent/style/index.ts
  src/styles/GlobalStyle/index.tsx
  src/utils/common.ts
Labels: feature

#123 프로젝트 페이지 공통 컴포넌트로 교체
  src/constants/common.ts
  src/mocks/data/project.ts
  src/pages/ProjectEditor/components/TechStackEditor/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/components/MemberEditor/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/components/ProjectTitleEditor/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/style/index.ts
  src/pages/ProjectItem/components/Title/index.tsx
  src/pages/ProjectItem/components/Title/style/index.ts
  src/pages/ProjectList/components/ProjectCard/index.tsx
  src/pages/ProjectList/components/ProjectListHeader/index.tsx
  src/pages/ProjectList/components/ProjectListHeader/style/index.ts
  src/pages/ProjectList/components/ProjectListToggle/index.tsx
  src/pages/ProjectList/style/index.ts
Labels: refactor

#126 버튼 그룹 및 모달 버그 수정
  src/components/Avatar/index.tsx
  src/components/Badge/index.tsx
  src/components/Button/index.tsx
  src/components/ButtonGroup/index.tsx
  src/components/ButtonGroup/style/index.ts
  src/components/Checkbox/index.tsx
  src/components/EmptyContent/index.tsx
  src/components/LoadingSpinner/index.tsx
  src/components/Modal/index.tsx
  src/components/Modal/store/index.ts
  src/components/Modal/stories/Modal.stories.tsx
  src/components/Modal/types/index.ts
  src/components/TextArea/index.tsx
  src/components/TextButton/index.tsx
  src/components/TextField/index.tsx
  src/components/ToggleSwitch/index.tsx
Labels: bug

#128 프로젝트 페이지 api 연결 1차
  .gitignore
  package-lock.json
  package.json
  src/Router.tsx
  src/apis/auth/index.ts
  src/apis/auth/type/index.ts
  src/components/Layout/Header/assets/avatar.svg
  src/components/Layout/Header/index.tsx
  src/components/Layout/Header/style/index.ts
  src/constants/api.ts
  src/constants/path.ts
  src/pages/PrivateRouter/index.tsx
  src/pages/ProjectList/components/ProjectCard/style/index.ts
  src/pages/ProjectList/components/ProjectCardList/index.tsx
  src/pages/ProjectList/components/ProjectListHeader/index.tsx
  src/pages/ProjectList/components/Searchbar/index.tsx
  src/pages/ProjectList/hooks/index.ts
  src/pages/ProjectList/hooks/useIsMyProjectSelected.ts
  src/pages/ProjectList/hooks/useProjectList.ts
  src/pages/ProjectList/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignIn/style/index.ts
  src/store/index.ts
  src/store/token/index.ts
  src/store/user/index.ts
  src/types/api.ts
  src/types/project.ts
Labels: feature

#130 토스트 & 툴팁 컴포넌트 구현 및 스토리 추가
  src/components/Toast/index.tsx
  src/components/Toast/store/index.ts
  src/components/Toast/stories/Toast.stories.tsx
  src/components/Toast/style/index.ts
  src/components/Toast/types/index.ts
  src/components/Tooltip/index.tsx
  src/components/Tooltip/store/index.ts
  src/components/Tooltip/stories/Tooltip.stories.tsx
  src/components/Tooltip/style/index.ts
  src/components/Tooltip/types/index.ts
Labels: feature

#135 feat: 프로젝트 수정 기능 구현
  src/pages/ProjectEditor/components/ButtonWithIcon/index.tsx
  src/pages/ProjectEditor/components/ButtonWithIcon/style/index.ts
  src/pages/ProjectEditor/components/DocumentTooltipList/index.tsx
  src/pages/ProjectEditor/components/SaveButton/index.tsx
  src/pages/ProjectEditor/components/TechStackEditor/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/components/MemberEditor/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/components/ThumbnailEditor/index.tsx
  src/pages/ProjectEditor/hooks/useCreateProjectMutation.ts
  src/pages/ProjectEditor/hooks/useEditProjectMutation.ts
  src/pages/ProjectEditor/index.tsx
  src/pages/ProjectItem/components/Title/style/index.ts
Labels: feature

#137 Fix: participant 누락
  src/pages/ProjectEditor/index.tsx
  src/pages/ProjectItem/components/Title/index.tsx
Labels: bug

#139 Fix: text errors
  src/pages/ProjectEditor/components/DescriptionEditor/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/components/MemberEditor/index.tsx
  src/pages/ProjectEditor/components/TitleEditor/components/ProjectTitleEditor/index.tsx
  src/pages/ProjectItem/components/Title/index.tsx
  src/pages/ProjectItem/components/Title/style/index.ts
Labels: bug

#144 Build: storybook
  .github/workflows/chromatic.yml
  .gitignore
  package.json
Labels: build

#145 툴팁 에러 수정 및 헤더 & 디바이더 컴포넌트 스토리 추가
  .storybook/main.ts
  package-lock.json
  package.json
  src/components/Divider/stories/Divider.stories.tsx
  src/components/Layout/Header/stories/Header.stories.tsx
  src/components/Modal/stories/Modal.stories.tsx
  src/components/Toast/stories/Toast.stories.tsx
  src/components/Tooltip/index.tsx
  src/components/Tooltip/store/index.ts
  src/components/Tooltip/stories/Tooltip.stories.tsx
  src/components/Tooltip/style/index.ts
Labels: bug, refactor, chore

#147 댓글 작성/삭제 API mutate로 구현
  package-lock.json
  package.json
  src/constants/query.ts
  src/pages/AlbumEditor/index.tsx
  src/pages/AlbumList/component/AlbumItem/index.tsx
  src/pages/AlbumList/hooks/index.ts
  src/pages/AlbumList/hooks/useDeleteAlbumReplyMutation.ts
  src/pages/AlbumList/hooks/usePostAlbumReplyMutation.ts
  src/pages/AlbumList/index.tsx
  src/pages/PostEditor/hooks/index.ts
  src/pages/PostEditor/index.tsx
  src/pages/PostList/components/PostItem/index.tsx
  src/pages/PostList/hooks/index.ts
  src/pages/PostList/hooks/useDeleteBoardReplyMutation.ts
  src/pages/PostList/hooks/usePostBoardReplyMutation.ts
  src/pages/PostList/index.tsx
Labels: feature

#149 Feat/link tooltip
  .gitignore
  package-lock.json
  package.json
  src/pages/ProjectEditor/components/DeleteButton/index.tsx
  src/pages/ProjectEditor/hooks/useDeleteProjectMutation.ts
  src/pages/ProjectEditor/index.tsx
  src/pages/ProjectItem/components/TooltipList/index.tsx
  src/pages/ProjectItem/components/TooltipList/style/index.ts
  src/styles/GlobalStyle/index.tsx
Labels: feature

#151 ✨ feat: role 한글로 변경
  src/constants/common.ts
  src/constants/query.ts
  src/pages/AlbumList/component/AlbumItem/index.tsx
  src/pages/PostList/components/PostItem/index.tsx
  src/types/album.ts
  src/utils/common.ts
Labels: feature

#154 refactor: 일일점검 페이지 레이아웃 수정
  src/pages/DailyCheck/index.tsx
  src/pages/DailyCheck/style/index.ts
Labels: refactor

#155 더 보기 버튼, 페이지네이션 컴포넌트 스토리 추가
  src/components/Avatar/stories/Avatar.stories.ts
  src/components/MoreButton/stories/MoreButton.stories.tsx
  src/components/Pagination/stories/Pagination.stories.tsx
Labels: feature
