Repository jei-community/frontend, pull requests merged in 2025-01, with the labels that each got.

#161 일부 컴포넌트 디자인 수정 및 버그 해결
  src/components/Button/style/index.ts
  src/components/Toast/stories/Toast.stories.tsx
  src/components/Tooltip/index.tsx
  src/components/Tooltip/style/index.ts
  src/components/Tooltip/types/index.ts
  src/main.tsx
  src/pages/ProjectEditor/components/DocumentTooltipList/index.tsx
  src/pages/ProjectEditor/components/SaveButton/index.tsx
  src/pages/ProjectItem/components/TooltipList/index.tsx
  src/pages/ProjectItem/components/TooltipList/style/index.ts
  src/styles/GlobalStyle/index.tsx
Labels: bug, feature, refactor

#163 포스트 리스트 에러 해결
  src/pages/Main/components/Post/PostItem.tsx
  src/pages/Main/index.tsx
  src/pages/PostList/index.tsx
Labels: bug

#171 TODO 해결
  src/pages/DailyCheck/components/MainContent/EmptyContent.tsx
  src/pages/DailyCheck/components/MainContent/index.tsx
  src/pages/DailyCheck/components/MainContent/style/index.ts
  src/pages/DailyCheck/components/Table/TBodyContent.tsx
  src/pages/DailyCheck/components/Table/index.tsx
  src/pages/DailyCheck/components/Tooltip/index.tsx
  src/pages/DailyCheck/index.tsx
  src/pages/Main/components/DailyCheck/Item.tsx
  src/pages/Main/components/DailyCheck/index.tsx
Labels: chore

#173 💄 style: 앨범 -> 추억 저장소로 이름 변경
  src/components/Layout/Header/index.tsx
  src/pages/AlbumEditor/index.tsx
  src/pages/AlbumList/index.tsx
Labels: feature

#170 refactor: 프로젝트 페이지 전체적인 디자인 시안에 맞게 수정
  src/components/DateText/index.tsx
  src/components/DateText/style/index.ts
  src/components/DateText/types/index.ts
  src/components/TechStack/index.tsx
  src/pages/ProjectItem/components/Description/hooks/index.ts
  src/pages/ProjectItem/components/Description/index.tsx
  src/pages/ProjectItem/components/TableOfContent/index.tsx
  src/pages/ProjectItem/components/TechStack/index.tsx
  src/pages/ProjectItem/components/Title/index.tsx
  src/pages/ProjectItem/index.tsx
  src/pages/ProjectList/components/ProjectCard/index.tsx
  src/pages/ProjectList/components/ProjectCard/style/index.ts
Labels: refactor

#179 feat: Route 에러 처리
  src/App.tsx
  src/components/ErrorBoundary/index.tsx
  src/components/Layout/Header/index.tsx
  src/hooks/useProjectDetails.ts
  src/pages/NotFound/index.tsx
  src/pages/ProjectItem/ProjectItemRouter/index.tsx
  src/pages/ProjectItem/components/TooltipList/index.tsx
Labels: feature

#185 3차 배포
  src/App.tsx
  src/components/ErrorBoundary/index.tsx
  src/components/Layout/Header/index.tsx
  src/hooks/useProjectDetails.ts
  src/pages/AlbumEditor/index.tsx
  src/pages/AlbumList/component/AlbumItem/style/index.ts
  src/pages/NotFound/index.tsx
  src/pages/ProjectItem/ProjectItemRouter/index.tsx
  src/pages/ProjectItem/components/TooltipList/index.tsx
  src/pages/ProjectItem/index.tsx
Labels: build

#193 💄 style: 메인 UI 수정
  src/pages/AlbumList/component/AlbumItem/index.tsx
  src/pages/Main/components/MyProject/style/index.ts
  src/pages/Main/components/Post/PostItem.tsx
  src/pages/Main/components/Post/style/index.ts
  src/pages/Main/index.tsx
  src/pages/PostList/components/PostItem/index.tsx
Labels: bug, feature

#191 Fix: link editor
  src/pages/ProjectEditor/components/DocumentTooltipList/components/LinkEditor/LinkItem/index.tsx
  src/pages/ProjectEditor/index.tsx
Labels: bug, feature

#189 fix: Pagination 내프로젝트 에러
  src/components/Pagination/index.tsx
  src/pages/ProjectList/hooks/useProjectList.ts
  src/pages/ProjectList/index.tsx
Labels: bug

#187 fix: 프로젝트 수정 페이지 권한 없을 경우 프로젝트 리스트 페이지로 리다이렉션
  src/pages/DailyCheck/components/Loading/index.tsx
  src/pages/ProjectItem/ProjectItemRouter/index.tsx
  src/pages/ProjectItem/index.tsx
  src/store/user/index.ts
Labels: bug

#195 💄 style: 메인페이지 내프로젝트 UI수정
  src/pages/AlbumsRouter/index.tsx
  src/pages/Main/components/MyProject/style/index.ts
  src/pages/Main/components/Post/style/index.ts
Labels: feature

#199 4차 배포
  src/components/Pagination/index.tsx
  src/components/ProjectThumbnail/style/index.ts
  src/pages/AlbumList/component/AlbumItem/index.tsx
  src/pages/AlbumsRouter/index.tsx
  src/pages/DailyCheck/components/Loading/index.tsx
  src/pages/Main/components/MyProject/style/index.ts
  src/pages/Main/components/Post/PostItem.tsx
  src/pages/Main/components/Post/style/index.ts
  src/pages/Main/index.tsx
  src/pages/PostEditor/style/index.ts
  src/pages/PostList/components/PostItem/index.tsx
  src/pages/ProjectEditor/components/DocumentTooltipList/components/LinkEditor/LinkItem/index.tsx
  src/pages/ProjectEditor/index.tsx
  src/pages/ProjectItem/ProjectItemRouter/index.tsx
  src/pages/ProjectItem/index.tsx
  src/pages/ProjectList/hooks/useProjectList.ts
  src/pages/ProjectList/index.tsx
  src/store/user/index.ts
Labels: build

#202 4차 배포
  src/pages/DailyCheck/components/MainContent/index.tsx
  src/pages/DailyCheck/components/Table/index.tsx
  src/pages/DailyCheck/index.tsx
  src/pages/DailyCheck/store/index.ts
  src/pages/Main/components/DailyCheck/ItemsWrapper.tsx
  src/pages/Main/components/DailyCheck/index.tsx
  src/pages/Main/components/DailyCheck/store/index.ts
Labels: build
